New UI interface
RealXuChe/cs353 pull request #4
Opened 2023-12-02 10:35 UTC by BamoSH

+ Added Frosted glass visual effects
+ Added title icon
+ Added tookcard icon
+ Added search bar UI

2023-12-07 08:44 UTC, RealXuChe requested changes

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +      <div className="h-[12rem] w-[31rem] bg-indigo-500 rounded-2xl overflow-hidden ">
I've noticed that the cards seem too large for mobile users. For example, the width of an iPhone 15 Pro Max is only 430 logical pixels. Considering the standard conversion of 16 pixels per rem, the card width should ideally be less than 26.875rem to fit on the screen. However, seems the current width of 31rem just won't fit.

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +        <div className="mx-12  pt-12 grid xl:grid-cols-3 lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 justify-center">
I previously wrote some responsive styles here to dynamically adjust the column count based on screen width, ensuring that cards didn't overlap. However, with your increase in card size, I've found there are overlap issues on narrower screens.

![图片](https://github.com/RealXuChe/cs353/assets/47659370/0928252a-6261-4461-b010-bd7b4aaea321)

Please fix this.

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +      <div className="rounded-2xl h-screen my-7 bg-[#F4F2F4] shadow-[inset_0rem_0.25rem_0.5rem_rgba(0,0,0,0.25)]">
I think you may have misused `h-screen` here since the height of the background should obviously adapt to the rows of cards, instead of a fixed value. Try adding, like one more row of dummy cards, and you will see why.

2023-12-07 08:44 UTC, RealXuChe commented on src/app/layout.tsx
> +          <div className="w-[108rem] ">{children}</div>
I don't see your intention changing here, again, please try to keep [Responsive design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design) in mind, prefer relative sizing to fixed values.

2023-12-07 08:44 UTC, RealXuChe commented on tailwind.config.js
> +        "3xl": "",
Is this code doing anything?

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +function ToolCardBg3({ meta }: { meta: ToolMeta }) {
If these versions of cards are unused, please remove them.

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +import title from "./icon/title.svg";
You can omit this import, it's unused.

2023-12-07 08:44 UTC, RealXuChe commented on src/app/page.tsx
> +import meta from "./toolbox/cidr-calculator/metadata";
seemingly unused import.

2023-12-16 15:40 UTC, BamoSH commented on src/app/page.tsx
> +        <div className="mx-12  pt-12 grid xl:grid-cols-3 lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 justify-center">
already fixed it

2023-12-16 15:41 UTC, BamoSH commented on src/app/page.tsx
> +      <div className="h-[12rem] w-[31rem] bg-indigo-500 rounded-2xl overflow-hidden ">
added Screen adaptation for phone size

2023-12-17 19:36 UTC, Anguei requested changes

2023-12-17 19:36 UTC, Anguei commented on src/app/page.tsx
> +function ToolCardBg({ meta }: { meta: ToolMeta }) {
The overlapping problem still exists. Please try to fix it.

2023-12-17 19:36 UTC, Anguei commented on src/app/Signup/page.tsx
> +              label="Emailaddress"
please add a space between words.

2023-12-17 19:36 UTC, Anguei commented on src/app/Signup/page.tsx
> +              label="Username"
please add a space between words.

2023-12-18 07:10 UTC, BamoSH commented on src/app/Signup/page.tsx
> +              label="Username"
actually it doesn't need to add a space between Username

2023-12-18 07:10 UTC, BamoSH commented on src/app/Signup/page.tsx
> +              label="Username"
![屏幕截图 2023-12-18 151019](https://github.com/RealXuChe/cs353/assets/144670219/2410e18a-af64-4bf8-aa6a-1408ac375438)
this is an example

2023-12-18 08:03 UTC, BamoSH commented
added new customization on tailwind.config.js, fix the margin size and card pattern at phone size. fix the incorrect font at Signin page's SIGNIN button.

2023-12-18 08:34 UTC, merged