feat: Sign in & Sign up Interface
RealXuChe/cs353 pull request #5
Opened 2023-12-08 10:31 UTC by BamoSH

![屏幕截图 2023-12-08 182958](https://github.com/RealXuChe/cs353/assets/144670219/2db44fd4-7d1b-4471-8de9-0d34f2ea189c)
![屏幕截图 2023-12-08 183033](https://github.com/RealXuChe/cs353/assets/144670219/338ae3e7-5a4b-4645-a024-03330659471f)

2023-12-11 04:22 UTC, RealXuChe requested changes

2023-12-11 04:22 UTC, RealXuChe commented on src/app/Signin/page.tsx
> +import Visibility from "@mui/icons-material/Visibility";
Did you forget to include your changes to `package.json`? It doesn't have `icons-material` included, and I'm getting `Module not found` error.

2023-12-11 09:13 UTC, BamoSH commented on src/app/Signin/page.tsx
> +import Visibility from "@mui/icons-material/Visibility";
Added @mui/icons-material package, it suppose to be running successfuly now

2023-12-12 11:19 UTC, RealXuChe approved these changes
LGTM!

2023-12-12 11:31 UTC, merged